### PR TITLE
Backport Refactors from PHS-Map

### PR DESCRIPTION
**Pull request by lishaduck**
And delete a lot of dead code.

### CODE REVIEW

**Comment by lishaduck** [comment]
@ParkerH27, is this all fine?

**Comment by lishaduck** [comment]
> @ParkerH27, is this all fine?

@PetalCat?

**Comment by lishaduck** [comment]
@ParkerH27?

**Comment by lishaduck** [comment]
@SocketSecurity ignore npm/sharp@0.32.6

**Review by PetalCat — APPROVED** [review]

**Pull request merged**
